src/views/auth_view.py
from flask import Blueprint, render_template, request, redirect, url_for, request
from facades.auth_facade import AuthFacade
from models.client_errors import ValidationError, AuthError

auth_blueprint = Blueprint("auth_view", __name__)


@auth_blueprint.route("/", methods=["GET", "POST"])
@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET":
            return render_template("login.html", user={})
        auth_facade = AuthFacade()
        auth_facade.login()

        return redirect(url_for("vacations_view.list"))
    except (ValidationError, AuthError) as error:
        return render_template("login.html", error="Invalid Email or Password.", user=error.model)


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET":
            return render_template("register.html", user={})
        auth_facade = AuthFacade()
        auth_facade.register()
        return redirect(url_for("vacations_view.list"))
    except ValidationError as err:
        return render_template("register.html", error=err.message, user=err.model)


@auth_blueprint.route("/logout")
def logout():
    auth_facade = AuthFacade()
    auth_facade.logout()
    return redirect(url_for("auth_view.login"))

src/views/likes_view.py
from flask import Blueprint, render_template, request, redirect, url_for
from facades.likes_facade import LikesFacade


likes_blueprint = Blueprint("likes_view", __name__)


@likes_blueprint.route("/likes/like/<int:id>")
def like(id):
    facade = LikesFacade()
    facade.like(id)
    return redirect(url_for("vacations_view.list"))

src/views/vacations_view.py
from flask import Blueprint, render_template, request, redirect, url_for, request, session, send_file
from models.client_errors import ValidationError, AuthError
from facades.auth_facade import AuthFacade
from facades.vacations_facade import VacationsFacade
from facades.countries_facade import CountriesFacade
from models.role_model import RoleModel
from utils.image_handler import ImageHandler


vacations_blueprint = Blueprint("vacations_view", __name__)

vacations_facade = VacationsFacade()


# Get list of all vacations
@vacations_blueprint.route("/vacations")
def list():
    try:
        # Block anonymous
        auth_facade = AuthFacade()
        auth_facade.block_anonymous()

        #  Get all vacations
        vacations_facade = VacationsFacade()
        all_vacations = vacations_facade.get_all_vacations()
        # If user is Admin display admin's template
        current_user = session.get("current_user")
        if current_user.get("role") == RoleModel.Admin.value:
            return render_template("admin_vacations.html", vacations=all_vacations)
        # Other way display User's template
        return render_template("user_vacations.html", vacations=all_vacations)
    except AuthError:
        return redirect(url_for("auth_view.login"))


# Get image file
@vacations_blueprint.route("/vacations/images/<string:image_name>")
def get_image(image_name):
    try:
        # Block anonymous. (I assume that just logged-in users can see images)
        auth_facade = AuthFacade()
        auth_facade.block_anonymous()
        # Get image path
        image_path = ImageHandler.get_image_path(image_name)
        # Send file to front-end
        return send_file(image_path)
    except AuthError:
        return redirect(url_for('auth_view.login'))


# Add vacation
@vacations_blueprint.route("/vacations/add", methods=["GET", "POST"])
def insert():
    try:
        # block non Admins
        auth_facade = AuthFacade()
        auth_facade.block_non_admin()

        # If method GET render template
        if request.method == "GET":
            countries_facade = CountriesFacade()
            countries = countries_facade.get_all_countries()
            return render_template("add_vacation.html", countries=countries, error={})

        # Other way add  vacation
        vacations_facade = VacationsFacade()
        vacations_facade.add_vacation()

        # Redirect to vacations page
        return redirect(url_for("vacations_view.list"))
    except AuthError:
        return redirect(url_for('auth_view.login'))
    except ValidationError as err:
        countries_facade = CountriesFacade()
        countries = countries_facade.get_all_countries()
        return render_template("add_vacation.html", countries=countries, error=err)


@vacations_blueprint.route("/vacations/<int:id>/edit", methods=["GET", "POST"])
def edit(id):

    try:
        # Block non Admins
        auth_facade = AuthFacade()
        auth_facade.block_non_admin()
        vacations_facade = VacationsFacade()
        if request.method == "GET":
            # Get vacation by id
            one_vacation = vacations_facade.get_one_vacation(id)
            # Get list of countries
            countries_facade = CountriesFacade()
            countries = countries_facade.get_all_countries()
            return render_template("edit_vacations.html", vacation=one_vacation, countries=countries)
        vacations_facade.update_vacation(id)
        return redirect(url_for("vacations_view.list"))
    except AuthError:
        return redirect(url_for('auth_view.login'))
    except ValidationError as err:
        # Get list of countries
        countries_facade = CountriesFacade()
        countries = countries_facade.get_all_countries()
        country_id = int(err.model.country)
        filtered_countries = [
            country for country in countries if country["country_id"] == country_id]
        if not len(filtered_countries):
            # If country not exists  reset country
            selected_country = "Select country"
            err.model.country = None
        else:
            selected_country = filtered_countries[0]["country"]
        # Fix country id and country name
        err.model.country_id, err.model.country = err.model.country, selected_country
        # Get current vacation image
        vacations_facade = VacationsFacade()
        err.model.image = vacations_facade.get_old_image(id)
        return render_template("edit_vacations.html", error=err.message, vacation=err.model, countries=countries)


@vacations_blueprint.route("/vacations/<int:id>/delete")
def delete(id):
    try:
        # Block non Admins
        auth_facade = AuthFacade()
        auth_facade.block_non_admin()
        # Delete vacation
        vacations_facade = VacationsFacade()
        vacations_facade.delete_vacation(id)
        # Redirect to vacations page
        return redirect(url_for("vacations_view.list"))
    except AuthError:
        return redirect(url_for('auth_view.login'))

src/templates/add_vacation.html
{% extends "layout.html" %}

{% block title %} Add Vacation {% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
                    {% set user = session.get("current_user") %}
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">{{ user.first_name }} {{
                                user.last_name }}</span></div>
                        <div><a href="{{ url_for('auth_view.logout') }}" class="logout">Logout</a></div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container form-container">
        <div class="row justify-content-center">
            <form method="post" id="vacationForm" class="col col-lg-4 col-md-6" enctype="multipart/form-data"
                onsubmit="validateVacationForm(event)">
                <h3>Add Vacation</h3>
                <div class="label">country</div>
                <div class="dropdown">
                    <button id="countrySelector" class="btn btn-outline-dark dropdown-toggle w-100" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Select country
                    </button>
                    <ul class="dropdown-menu w-100 countries-list">
                        {% for c in countries %}
                        <li onclick="selectCountry('{{ c.country }}','{{ c.country_id }}')">{{ c.country }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <input type="hidden" id="countryBox" name="country" class="form-control" required>
                <label for="description">description</label>
                <textarea id="description" name="description" class="form-control" required></textarea>
                <label for="startDate">start on</label>
                <input type="date" id="startDate" name="start_date" class="form-control" required onchange="validateStartDate()">
                <label for="endDate">end on</label>
                <input type="date" id="endDate" name="end_date" class="form-control" required onchange="validateEndDate()">
                <label for="price">price</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1">$</span>
                    <input type="number" id="priceBox" name="price" step="0.01" class="form-control" aria-label="Price"
                        aria-describedby="basic-addon1" onblur="this.value=parseFloat(this.value).toFixed(2)" min="0"
                        max="10000" required>
                </div>
                <label for="image">cover image</label>
                <div class="file-container">
                    <img id="preview" src="{{ url_for('vacations_view.get_image', image_name ='_' ) }}"
                        alt="Image not selected" class="rounded  w-100 preview">
                    <div class="w-100">
                        <span id="imgBtn" class="btn btn-sm btn-file w-50 m-auto">
                            Add image <input type="file" id="image" name="image" accept="image/*"
                                onchange="displayImage()" required>
                        </span>
                    </div>
                </div>
                {% if error %}
                <div class="alert alert-light" role="alert">{{ error }}</div>
                {% endif %}
                <div>
                    <button type="submit" class="btn btn-lg btn-dark ">Add Vacation</button>
                </div>
                <div>
                    <a href="{{ url_for('vacations_view.list') }}" class="btn btn-lg btn-dark-outline ">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

src/templates/admin_vacations.html
{% extends "layout.html" %}

{% block title %}Vacations{% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3">
                    <a class="btn btn-md btn-outline-dark btn-add" href="{{ url_for('vacations_view.insert') }}"><i
                            class="fa-solid fa-plus"></i> Add Vacation</a>
                </div>
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-8 offset-sm-8 offset-xs-6">
                    {% set user = session.get("current_user") %}
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">{{ user.first_name }} {{
                                user.last_name
                                }}</span></div>
                        <div><a href="{{ url_for('auth_view.logout') }}" class="logout">Logout</a></div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container-fluid flex-xl-nowrap">
        <div class="row">
            {% for vacation in vacations %}
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="card" style="width: 26rem;">
                    <a href="{{ url_for('vacations_view.edit', id=vacation.id ) }}"
                        class="btn btn-sm btn-light edit-btn"><i class="fa-solid fa-pen"></i>Edit</a>
                    <button class="btn btn-sm btn-light delete-btn"
                        onclick="deleteVacation(`{{ url_for('vacations_view.delete', id=vacation.id)  }}`)"><i
                            class="fa-solid fa-trash"></i>Delete</button>
                    <span class="card-city">{{ vacation.country }}</span>
                    <img src="{{ url_for('vacations_view.get_image', image_name = (vacation.image if vacation.image else '_')) }}"
                        class="card-img-top" alt="{{ vacation.country }}">
                    <div class="card-head">
                        <i class="fa-solid fa-calendar"></i>
                        {{ vacation.start_date }} - {{ vacation.end_date }}
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ vacation.description }}</p>
                    </div>
                    <div card="card-footer">
                        <button class="btn btn-lg btn-dark" style="width:100%">
                            ${{ '%.2f'|format(vacation.price) }}
                        </button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}

src/templates/edit_vacations.html
{% extends "layout.html" %}

{% block title %} Add Vacation {% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
                    {% set user = session.get("current_user") %}
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">{{ user.first_name }} {{
                                user.last_name }}</span></div>
                        <div><a href="{{ url_for('auth_view.logout') }}" class="logout">Logout</a></div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container form-container">
        <div class="row justify-content-center">
            <form method="post" id="vacationForm" class="col col-lg-4 col-md-6" enctype="multipart/form-data"
                onsubmit="validateVacationForm(event)">
                <h3>Edit Vacation</h3>
                <div class="label">country</div>
                <div class="dropdown">
                    <button id="countrySelector" class="btn btn-outline-dark dropdown-toggle w-100" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ vacation.country }}
                    </button>
                    <ul class="dropdown-menu w-100 countries-list">
                        {% for c in countries %}
                        <li onclick="selectCountry('{{ c.country }}','{{ c.country_id }}')">{{ c.country }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <input type="hidden" id="countryBox" value="{{ vacation.country_id }}" name="country"
                    class="form-control" required>
                <label for="description">description</label>
                <textarea id="description" name="description" class="form-control"
                    required>{{ vacation.description }}</textarea>
                <label for="startDate">start on</label>
                <input type="date" id="startDate" name="start_date" value="{{ vacation.start_date }}"
                    class="form-control" required>
                <label for="endDate">end on</label>
                <input type="date" id="endDate" name="end_date" value="{{ vacation.end_date }}" class="form-control"
                    onchange="validateEndDate()" required>
                <label for="priceBox">price</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1">$</span>
                    <input type="number" id="priceBox" name="price" step="0.01" value="{{ vacation.price }}"
                        class="form-control" aria-label="Price" aria-describedby="basic-addon1"
                        onblur="this.value=parseFloat(this.value).toFixed(2)" min="0" max="10000" required>
                </div>
                <label for="image">cover image</label>
                <div class="file-container">
                    <img id="preview"
                        src="{{ url_for('vacations_view.get_image', image_name = (vacation.image if vacation.image else '_')) }}"
                        alt="{{ vacation.country }}" class="rounded  w-100 preview">
                    <div class="w-100">
                        <span id="imgBtn" class="btn btn-sm btn-file w-50 m-auto">
                            Change image <input type="file" id="image" name="image" accept="image/*"
                                onchange="displayImage()">
                        </span>
                    </div>
                </div>
                {% if error %}
                <div>
                    <div class="alert alert-light" role="alert">{{ error }}</div>
                </div>
                {% endif %}
                <div>
                    <button type="submit" class="btn btn-lg btn-dark ">Update Vacation</button>
                </div>
                <div>
                    <a href="{{ url_for('vacations_view.list') }}" class="btn btn-lg btn-dark-outline ">Cancel</a>
                </div>

            </form>
        </div>
    </div>
</main>
{% endblock content %}

src/templates/header.html
<header class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
            {% set user = session.get("current_user") %}
            <div class="user-container">
                <div class="welcome-user">Welcome: <span class="user-name">{{ user.first_name }} {{ user.last_name }}</span></div>
                <div><a href="{{ url_for('auth_view.logout') }}" class="logout">Logout</a></div>
            </div>
            <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
        </div>
    </div>
</header>

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
</head>

<body>
        {% block content %}{% endblock content %}
</body>

</html>

src/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">Guest</span></div>
                        <div><span class="logout">Please login to continue...</span></div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container form-container">
        <div class="row justify-content-center">
            <form method="post" class="col col-lg-4 col-md-6">
                <h3>Login</h3>
                <label for="email">email</label>
                <input type="email" id="email" name="email" value="{{ user.email }}" class="form-control" required>
                <label for="password">password</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-eye"
                            id="passwordIcon"></i></span>
                    <input type="password" id="password" name="password" class="form-control" aria-label="Password"
                        aria-describedby="basic-addon1" minlength="4" required>
                </div>
                <div class="btn-row">
                    <button type="submit" class="btn btn-dark">Login</button>
                </div>

                {% if error %}
                <div class="alert alert-light" role="alert">{{ error }}</div>
                {% endif %}

                <div class="question">don't have an account?</div>
                <div>
                    <a href="{{ url_for('auth_view.register') }}">register now</a>
                </div>
            </form>
        </div>
        {# 👇 This script allow to show / hide passwords #}
        <script src="{{ url_for('static', filename='js/password.js') }}"></script>
    </div>
</main>
{% endblock content %}

src/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">Guest</span></div>
                        <div><a href="{{ url_for('auth_view.login') }}" class="logout">Please login to continue...</a>
                        </div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container form-container">
        <div class="row justify-content-center">
            <form method="post" class="col col-lg-4 col-md-6">
                <h3>Register</h3>
                <label for="first-name">first name</label>
                <input type="text" id="first-name" name="first_name" value="{{ user.first_name }}" class="form-control"
                    required minlength="2" maxlength="32">
                <label for="last-name">last name</label>
                <input type="text" id="last-name" name="last_name" value="{{ user.last_name }}" class="form-control"
                    required required minlength="2" maxlength="32">
                <label for="email">email</label>
                <input type="email" id="email" name="email" value="{{ user.email }}" class="form-control" required>
                <label for="password"> password</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-eye"
                            id="passwordIcon"></i></span>
                    <input type="password" id="password" name="password" class="form-control" aria-label="Password"
                        aria-describedby="basic-addon1" required minlength="4">
                </div>
                <div class="btn-row">
                    <button type="submit" class="btn btn-dark">Register</button>
                </div>

                {% if error %}
                <div class="alert alert-light" role="alert">{{ error }}</div>
                {% endif %}

                <div class="question">already a member?</div>
                <div>
                    <a href="{{ url_for('auth_view.login') }}">login</a>
                </div>
            </form>
        </div>
        {# 👇 This script allow to show / hide passwords #}
        <script src="{{ url_for('static', filename='js/password.js') }}"></script>
    </div>
</main>
{% endblock content %}

src/templates/user_vacations.html
{% extends "layout.html" %}

{% block title %}Vacations{% endblock title %}
{% block content %}
<header>
    <div class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-md-2 col-sm-2 coll-xs-3 offset-md-10 offset-sm-10 offset-xs-9">
                    {% set user = session.get("current_user") %}
                    <div class="user-container">
                        <div class="welcome-user">Welcome: <span class="user-name">{{ user.first_name }} {{
                                user.last_name }}</span></div>
                        <div><a href="{{ url_for('auth_view.logout') }}" class="logout">Logout</a></div>
                    </div>
                    <div class="ico-container"><i class="fa-solid fa-user user-ico"></i></div>
                </div>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="container-fluid">
        <div class="row">
            {% for vacation in vacations %}
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="card" style="width: 26rem;">
                    <a href="{{ url_for( 'likes_view.like', id=vacation.id ) }}"
                        class="btn btn-sm {{'btn-reddish' if vacation.liked==1 else 'btn-light' }} like-btn">
                        <i class="{{ 'fa-solid fa-heart' if vacation.liked==1 else 'fa-regular fa-heart' }}"></i>
                        <span class="counter">{{ vacation.likes_count }}</span>Likes
                    </a>
                    <span class="card-city">{{ vacation.country }}</span>
                    <img src="{{ url_for('vacations_view.get_image', image_name = (vacation.image if vacation.image else '_')) }}"
                        class="card-img-top" alt="{{ vacation.country }}">
                    <div class="card-head">
                        <i class="fa-solid fa-calendar"></i>
                        {{ vacation.start_date }} - {{ vacation.end_date }}
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ vacation.description }}</p>
                    </div>
                    <div card="card-footer">
                        <button class="btn btn-lg btn-dark" style="width:100%">${{ '%.2f'|format(vacation.price)
                            }}</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}